### ISSUE TITLE
PAY.JP利用規約 内にdummy text が残っている

### ISSUE THREAD

**Issue by ttsuru** [payjp/user-docs#2]
1. 登録取消等

> 1. 当社及び購入者は、それぞれ●日前までに当社所定の方法で相手方に通知することにより、購入者の登録を取り消すことができます。

「●日前」とダミーテキストになっているようです。ご確認をお願いいたします。

**Comment by keketa** [comment]
大変失礼しました。正しくは30日前となっていますので、再度ご確認をおねがいします。
